package edu.advising.report.html;

import edu.advising.report.ReportFormatter;

import java.util.List;
import java.util.stream.Collectors;

public class HtmlFormatter implements ReportFormatter {

    @Override
    public String formatTable(List<String> headers, List<List<String>> rows) {
        StringBuilder sb = new StringBuilder("<table border=\"1\" cellpadding=\"6\">\n<thead><tr>");
        for (String h : headers) sb.append("<th>").append(h).append("</th>");
        sb.append("</tr></thead>\n<tbody>\n");
        for (List<String> row : rows) {
            sb.append("<tr>");
            for (String cell : row) sb.append("<td>").append(cell).append("</td>");
            sb.append("</tr>\n");
        }
        sb.append("</tbody>\n</table>");
        return sb.toString();
    }

    @Override
    public String formatHeader(String institution, String reportName, String generatedBy) {
        return String.format("""
                <header>
                  <h1>%s</h1>
                  <h2>%s</h2>
                  <p>Generated by: %s</p>
                </header>
                """, institution, reportName, generatedBy);
    }

    @Override
    public String formatFooter(String notes) {
        return "<footer><p>" + notes + "</p></footer>";
    }
}
