package edu.advising.users;

import edu.advising.core.DatabaseManager;

import java.sql.*;

/**
 * UserFactory - Factory Pattern Implementation
 * Creates appropriate user objects and persists them to database
 */
public class UserFactory {
    private DatabaseManager dbManager;

    public UserFactory() {
        this.dbManager = DatabaseManager.getInstance();
    }

    /**
     * Factory method to create users based on type
     */
    public User createUser(String userType, String username, String password,
                           String email, String firstName, String lastName, String... additionalInfo) {
        User user = null;

        switch (userType.toUpperCase()) {
            case "STUDENT":
                if (additionalInfo.length >= 1) {
                    user = new Student(username, password, email, firstName, lastName,
                            additionalInfo[0]); // studentId
                }
                break;
            case "FACULTY":
                if (additionalInfo.length >= 2) {
                    user = new Faculty(username, password, email, firstName, lastName,
                            additionalInfo[0], // employeeId
                            additionalInfo[1]); // department
                }
                break;
            default:
                throw new IllegalArgumentException("Unknown user type: " + userType);
        }

        if (user != null) {
            saveUserToDatabase(user, additionalInfo);
        }

        return user;
    }

    private void saveUserToDatabase(User user, String... additionalInfo) {
        try {
            String userSql = "INSERT INTO users (username, password, user_type, first_name, last_name, email) VALUES (?, ?, ?, ?, ?, ?)";

            // Retrieving the user id generated by the database, and setting it on this object.
            user.setId(dbManager.executeInsert(userSql,
                    user.getUsername(),
                    user.password,
                    user.getUserType(),
                    user.getFirstName(),
                    user.getLastName(),
                    user.getEmail()));

            // Insert into specific user type table
            if (user instanceof Student) {
                Student student = (Student) user;
                String studentSql = "INSERT INTO students (id, student_id, gpa) VALUES (?, ?, ?)";
                dbManager.executeUpdate(studentSql, user.getId(), student.getStudentId(), student.getGpa());
            } else if (user instanceof Faculty) {
                Faculty faculty = (Faculty) user;
                String facultySql = "INSERT INTO faculty (id, employee_id, department) VALUES (?, ?, ?)";
                dbManager.executeUpdate(facultySql, user.getId(), faculty.getEmployeeId(), faculty.getDepartment());
            }

            System.out.println("User created successfully with ID: " + user.getId());
        } catch (SQLException e) {
            System.err.println("Insert failed: " + e.getMessage());
            throw new RuntimeException("Error saving user to database", e);
        }
    }

    /**
     * Retrieve user from database by userId
     */
    private User getUserByParam(String sql, String param) {
        try {
            return dbManager.executeQuery(sql,rs ->
            {
                if (rs.next()) {
                    String userType = rs.getString("user_type");
                    User user = null;

                    if ("STUDENT".equals(userType)) {
                        user = new Student(
                                rs.getString("username"),
                                rs.getString("password"),
                                rs.getString("email"),
                                rs.getString("s_fname"),
                                rs.getString("s_lname"),
                                rs.getString("student_id")
                        );
                        ((Student) user).setGpa(rs.getBigDecimal("gpa"));
                    } else if ("FACULTY".equals(userType)) {
                        user = new Faculty(
                                rs.getString("username"),
                                rs.getString("password"),
                                rs.getString("email"),
                                rs.getString("f_fname"),
                                rs.getString("f_lname"),
                                rs.getString("employee_id"),
                                rs.getString("department")
                        );
                    } else if ("ADMIN".equals(userType)) {
                        Admin admin = new Admin(
                                rs.getString("username"),
                                rs.getString("password"),
                                rs.getString("email"),
                                rs.getString("s_fname"),
                                rs.getString("s_lname")
                        );
                        admin.setEmployeeId(rs.getInt("a_employee_id"));
                        admin.setAccessLevel(rs.getString("access_level"));
                        user = admin;
                    }

                    if (user != null) {
                        user.setId(rs.getInt("id"));
                    }
                    return user;
                }
                return null;
            }, param);
        } catch (SQLException e) {
            throw new RuntimeException("Error retrieving user", e);
        }
    }

    /**
     * Retrieve user from database by userId
     */
    public User getUserById(int userId) {
        String sql = "SELECT u.*, u.first_name as s_fname, u.last_name as s_lname, " +
                "s.student_id, s.gpa, u.first_name as f_fname, u.last_name as f_lname, " +
                "f.employee_id, f.department, a.employee_id as a_employee_id, a.access_level " +
                "FROM users u " +
                "LEFT JOIN students s ON u.id = s.id " +
                "LEFT JOIN faculty f ON u.id = f.id " +
                "LEFT JOIN admins a ON u.id = a.id " +
                "WHERE u.id = ?";
        return this.getUserByParam(sql, String.valueOf(userId));
    }

    /**
     * Retrieve user from database by username
     */
    public User getUserByUsername(String username) {
        String sql = "SELECT u.*, u.first_name as s_fname, u.last_name as s_lname, " +
                "s.student_id, s.gpa, u.first_name as f_fname, u.last_name as f_lname, " +
                "f.employee_id, f.department, a.employee_id as a_employee_id, a.access_level " +
                "FROM users u " +
                "LEFT JOIN students s ON u.id = s.id " +
                "LEFT JOIN faculty f ON u.id = f.id " +
                "LEFT JOIN admins a ON u.id = a.id " +
                "WHERE u.username = ?";
        return this.getUserByParam(sql, username);
    }
}