package edu.advising.report.pdf;

import edu.advising.report.ReportFormatter;

import java.util.List;
import java.util.stream.Collectors;

public class PdfFormatter implements ReportFormatter {

    @Override
    public String formatTable(List<String> headers, List<List<String>> rows) {
        StringBuilder sb = new StringBuilder();
        String headerRow = headers.stream()
                .map(h -> String.format("%-20s", h))
                .collect(Collectors.joining(" | "));
        sb.append(headerRow).append("\n");
        sb.append("-".repeat(headerRow.length())).append("\n");
        for (List<String> row : rows) {
            sb.append(row.stream()
                    .map(c -> String.format("%-20s", c))
                    .collect(Collectors.joining(" | ")))
              .append("\n");
        }
        return sb.toString();
    }

    @Override
    public String formatHeader(String institution, String reportName, String generatedBy) {
        return String.format("""
                ============================================================
                  %s
                  Report: %s
                  Generated by: %s
                ============================================================
                """, institution, reportName, generatedBy);
    }

    @Override
    public String formatFooter(String notes) {
        return "\n------------------------------------------------------------\n" + notes + "\n";
    }
}
